### ISSUE TITLE
Thuyết trình đề tài(11-03-2016)

### ISSUE THREAD

**Issue by rinodung** [rinodung/webgoat#17]
**Đề tài:**  So sánh quy trình kiểm duyệt ứng dụng của Android(Google Play) và Apple( App Store)

**Miệu tả:** Khi chúng ta viết một ứng dụng di động muốn cho người dùng có thể tải về và dùng thì cần đặt chúng(upload) lên chợ ứng dụng nào đó. Mà cụ thể là **Android(Google Play) và Apple( App Store)**. 

Tùy theo chính sách của công ty mà quy trình kiểm duyệt khác nhau, nhiệm vụ của chúng ta là tìm hiểu 2 quy trình kiểm duyệt đó để so sánh.

**Phân công:**
1. Android(Google Play): Thúy, Kha, Lương
2. Apple( App Store): Dũng, Hạnh, Hậu

**Slide:** https://docs.google.com/presentation/d/1QrJTwbtVDW4LHb6cExU1tDyO-ZqaRe0-e9fiOwbjToc/edit#slide=id.p64
**Tham khảo:**
**Google Play:**
https://support.google.com/googleplay/android-developer/answer/113469?hl=en
http://www.chienluocmoi.com/2014/07/huong-dan-up-game-len-google-play.html

**App Store:**
http://genk.vn/apps-games/apple-duyet-ung-dung-len-appstore-nhu-the-nao-20140903164203372.chn
https://www.raywenderlich.com/8003/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-1
https://www.raywenderlich.com/8045/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-2

http://www.slideshare.net/nagaharish_movva/how-to-avoid-app-store-rejection

https://www.youtube.com/playlist?list=PLzrVYRai0riQnNpYRJcGImQK5Lyqs-jZM

**Comment by luongnguyenduc** [comment]
là tuần sau báo cáo hả anh Dũng, sao gấp quá vậy

**Comment by rinodung** [comment]
mới có deadline mới là thứ 6 (11-03-2016) nhá mọi người. 

> Do Thầy Hậu bận công tác, nên các lớp trưởng thống nhất dời buổi học (Bào cáo) môn AN TOÀN BMTT tối thứ Sáu 04/03/2016 sang chiều thứ 7 - 12/03/2016.
Như vậy, sẽ có 2 buổi báo cáo liên tục: tối 11/03/2016 và chiều 12/03/2016.

**Comment by luongnguyenduc** [comment]
Anh Kha, chị Thúy có tìm đc gì không? em thấy cách kiểm duyệt giống chuyện nội bộ, bí mật công nghệ ấy, chả có cái nào nói chi tiết vào

**Comment by Dunghanh** [comment]
ĐÚNG LÀ CÁ GÌ CŨNG KHÓ! GIÀ MÀ CÒN HAM HỐ ĐI HỌC CHO KHỔ NÈ GIỜI!

**Comment by Dunghanh** [comment]
CHẮC HẠNH ĐƯA MẤY CÁI LỖI LÊN HEN , 2 BẠN CÒN LẠI LÀM CÁI KHÓ NHA!

**Comment by mickey123456** [comment]
Trong đó có em nữa hả
Vào 08-03-2016 03:48, "Dunghanh" <notifications@github.com> đã viết:

**Comment by rinodung** [comment]
Mọi người đừng quá lo lắng, em sẽ cố gắng làm slide và cung cấp link cho mọi người đọc để thuyết trình.. Chắc tối mai là có cho mọir người... Cứu em môn triết là được....

**Comment by Dunghanh** [comment]
De tui soan goi file ghi am cho nha
Vào 08-03-2016 22:03, "Dong Dung" <notifications@github.com> đã viết:

**Comment by rinodung** [comment]
hehe ok chị đẹp, không biết sẽ thi cái gì thôi ak??? Chị biết gì thì giúp em bên đây nhá: https://github.com/rinodung/triet-hoc/issues/1

**Comment by Dunghanh** [comment]
Ok
Vào 08-03-2016 22:07, "Dong Dung" <notifications@github.com> đã viết:

**Comment by rinodung** [comment]
Phần apple em đã làm xong mấy chị coi slide nhé.
https://docs.google.com/presentation/d/1QrJTwbtVDW4LHb6cExU1tDyO-ZqaRe0-e9fiOwbjToc/edit

**Nội dung chi tiết**
http://genk.vn/apps-games/apple-duyet-ung-dung-len-appstore-nhu-the-nao-20140903164203372.chn
https://www.raywenderlich.com/8003/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-1
https://www.raywenderlich.com/8045/how-to-submit-your-app-to-apple-from-no-account-to-app-store-part-2

http://www.slideshare.net/nagaharish_movva/how-to-avoid-app-store-rejection

**Comment by rinodung** [comment]
@luongnguyenduc , @doankha  sao rồi???

**Comment by Dunghanh** [comment]
CAM ON NHIEU

**Comment by doankha** [comment]
- Bạn Dũng và các bạn trong nhóm mếm!Dạo này Kha quá bận không còn thời gian để làm project môn này.
- Lẻ ra kha nên nói với nhóm sớm để nhóm biết sắp xếp kế hoạch làm bài.Nhưng do áp lực công việc+ với deadline nhiều quá mình ko làm nổi.
- Môn này mình ít đi học nên cũng ko biết gì , mình quyết định học lại.
- Bạn Dũng rất giỏi hy vọng bạn sẽ dắt các bạn còn lại trong nhóm.
- Thành thật xin lổi các bạn.
- Xin lỗi Dũng mình đã làm khó cho bạn.

**Comment by luongnguyenduc** [comment]
Em sẽ ráng tìm hiểu xong trong tối nay cám ơn anh

**Comment by rinodung** [comment]
@luongnguyenduc em tìm hiểu và làm slide luôn nhé. Em sẽ thuyết trình phần này, chủ yếu là mình đưa ra cái luồng làm việc để đẩy một app lên google store, không có tính đúng sai ở đây chủ yếu mình hiểu sao nói vậy. Em rán làm cái Google Store để mình làm cái kết luận so sánh hai bên em nhé. reply lại cho anh để anh biết.
@doankha cố lên nhá

**Comment by luongnguyenduc** [comment]
Okie a, em đang làm, em sẽ update những gì làm đc trước sáng mai

**Comment by rinodung** [comment]
bên anh để đăng một app cần phải có tài khoản phí là 99$ một năm, bên em nhấn mạnh điểm phí đăng tải ứng dụng(Google Play là 25$) em nhá.

Nhưng anh chưa hiểu 25$ này là để đăng một ứng dụng hay để tạo một tài khoản rồi muốn đăng bao nhiêu thì đăng ta?

![android app signup](https://cloud.githubusercontent.com/assets/7805715/13636831/920ce36a-e636-11e5-9de5-0a1099abca38.png)

**Comment by luongnguyenduc** [comment]
Theo em đọc là 25$ để mở tài khoản thôi rồi muốn đăng bao nhiêu thì đăng,

mà cho em hỏi đăng ký đề tài với nhóm CNPM ở đâu vậy ạ?  em coi trên courses.uit.edu.vn mà ko thấy chỗ ĐK

**Comment by luongnguyenduc** [comment]
Em đã update vào trong slide mặc dù khá tệ, em sẽ tiếp tục tìm hiểu và update thêm

**Comment by rinodung** [comment]
liên hệ anh Phúng em nhé, anh cũng chưa đăng ký. chừng nào báo cáo ta?

2016-03-09 21:58 GMT+07:00 luongnguyenduc <notifications@github.com>:

> Em đã update vào trong slide mặc dù khá tệ, em sẽ tiếp tục tìm hiểu và
> update thêm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rinodung/webgoat/issues/17#issuecomment-194333432>.
>



-- 
Đồng Tiến Dũng
01699938919
University of Information Technology

**Comment by mickey123456** [comment]
Hnay hết hạn đăng ký CNPM đó các đồng chí
Vào 09-03-2016 23:52, "Dong Dung" <notifications@github.com> đã viết:

**Comment by luongnguyenduc** [comment]
Cám ơn anh Dũng, em cũng đang chưa biết làm nhóm với ai :))

**Comment by rinodung** [comment]
Thế là đã xong chiều nay(11-03-2016) nhóm mình sẽ báo cáo : https://docs.google.com/presentation/d/1QrJTwbtVDW4LHb6cExU1tDyO-ZqaRe0-e9fiOwbjToc/edit#slide=id.g11d593724e_11_28

**Comment by mickey123456** [comment]
gioi ta

2016-03-11 11:34 GMT+07:00 Dong Dung <notifications@github.com>:

> Thế là đã xong chiều nay(11-03-2016) nhóm mình sẽ báo cáo :
> https://docs.google.com/presentation/d/1QrJTwbtVDW4LHb6cExU1tDyO-ZqaRe0-e9fiOwbjToc/edit#slide=id.g11d593724e_11_28
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rinodung/webgoat/issues/17#issuecomment-195175825>.
>



-- 
Tran Thi Thu Thuy
Mobile: 0909.714.699

**Comment by mickey123456** [comment]
cụ thể ai thuyết trình vậy em

On Fri, Mar 11, 2016 at 12:02 PM, Trần Thị Thu Thúy <thuyttt1985@gmail.com>
wrote:

> gioi ta
>
> 2016-03-11 11:34 GMT+07:00 Dong Dung <notifications@github.com>:
>
>> Thế là đã xong chiều nay(11-03-2016) nhóm mình sẽ báo cáo :
>> https://docs.google.com/presentation/d/1QrJTwbtVDW4LHb6cExU1tDyO-ZqaRe0-e9fiOwbjToc/edit#slide=id.g11d593724e_11_28
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rinodung/webgoat/issues/17#issuecomment-195175825>.
>>
>
>
>
> --
> Tran Thi Thu Thuy
> Mobile: 0909.714.699
>
>


-- 
Tran Thi Thu Thuy
Mobile: 0909.714.699

**Comment by mickey123456** [comment]
đây là slide chị có chỉnh lại và chèn thêm hình, mấy đứa thấy thế nào
[Bao cao An toan va bao mat mang thong tin.pptx](https://github.com/rinodung/webgoat/files/168556/Bao.cao.An.toan.va.bao.mat.mang.thong.tin.pptx)

**Comment by rinodung** [comment]
Thầy hậu không yêu cầu mọi người cùng thuyết trình, thuyết trình tính điểm chung nên các chị đừng lo lắng,
Mình chia 2 nhóm nhỏ Em và lương đại diện cho hai nhóm nhỏ sẽ báo cáo..
