### ISSUE TITLE
[khẩn]Báo cáo công nghệ phần mềm - LƯƠNG

### ISSUE THREAD

**Issue by rinodung** [rinodung/webgoat#18]
Hi lương, 
đây là báo cáo môn công nghệ phần mềm tiên tiến

Nhóm mình sẽ làm về code inspection cụ thể là ngôn ngữ PHP với nội dung 4 phần: (em phần 1, 2), anh(3,4)
1. Giới thiệu về code inspection
   - code inspection là gì?
   - tại sao phải sử dụng code inspection (kiểm tra lỗi, chất lượng code tốt, chuẩn hoá khi việc nhóm...)
2. Các chuẩn hoá cơ bản: tuỳ theo ngôn ngữ mà chúng ta sẽ có những chuẩn hoá khác nhau: PHP(pear, psr1, psr2, wordpress, drupal....), JAVA(... em tìm nhé)
3. demo code inspection với ngôn ngữ php theo chuẩn wordpress, drupal
4. kết luận
Cập nhật nội dung trực tiếp lên slide này luôn...
https://docs.google.com/presentation/d/1Q1GlWwZdfYZfo6v3s_i3KSCs0atzvofujwNf_7AVWlw/edit

Trả lời mail lại cho anh khi nhận được, vì hơi gấp chậm nhất là tối chủ nhật(27/03/2016) em nhé

**Comment by luongnguyenduc** [comment]
Ok anh, em sẽ tìm hiểu và cập nhật vào slide, em tập trung vào chuẩn hóa của java thôi phải ko anh?

**Comment by rinodung** [comment]
uhm em

**Comment by rinodung** [comment]
Câu hỏi Quiz 1: 
[Quiz 1 Question - Nhom 16- ch1502028 Dong Tien Dung - ch1502035 Nguyen Duc Luong.docx](https://github.com/rinodung/webgoat/files/191832/Quiz.1.Question.-.Nhom.16-.ch1502028.Dong.Tien.Dung.-.ch1502035.Nguyen.Duc.Luong.docx)
