### ISSUE TITLE
Thông Báo Thi Môn An Toàn và Bảo Mật Thông Tin(08/04/2016)

### ISSUE THREAD

**Issue by rinodung** [rinodung/webgoat#19]
Thời gian: 17h00 Tối thứ 6 ngày 08/04/2016

Vậy là còn 1 tuần để ôn thi. Mọi người có tài liệu ôn thi, hình thức thi(mở đóng) thì comment xuống đây  để giúp mọi người nắm thông tin nhé

**Comment by rinodung** [comment]
Câu hỏi ôn thi:

1. Trình bày các khái niệm căn bản: security, availability, confidentiality, integrity, vulnerability, threat, risk,...
2. Trình bày ưu và nhược điểm của 2 hướng tiếp cận trong việc xây dựng chương trình đảm bảo ATTT trong doanh nghiệp là top-down và bottom-up.
3. Security through obscurity là gì?
4. Ý tưởng chính của hướng tiếp cận defense in depth là gì?
5. Phân tích sự ràng buộc giữa việc đảm bảo an toàn thông tin và khả năng truy cập vào hệ thống.
6. Trình bày 3 loại công cụ dùng để đảm bảo an toàn thông tin là công cụ hành chính, kỹ thuật và vật lý.
7. Trình bày các loại rủi ro (về ATTT) thường gặp trong hoạt động của một tổ chức.
8. Trình bày kỹ thuật, các bước chính trong việc ước lượng rủi ro đối với 2 hướng tiếp cận quantitative và qualitative.
9. An toàn ứng dụng web: Trình bày cơ chế hoạt động của các loại lỗi SQL injection, parameter injection, broken authentication, XSS
10. **Mã hoá:** Phân biệt giữa mã hoá đối xứng và bất đối xứng. So sánh các ưu và nhược điểm của mã hoá đối xứng và bất đối xứng
11. Giải thích tấn công mã hoá thay thế (substitution) bằng kỹ thuật thống kê tần suất xuất hiện ký tự (English letter frequency)
12. Phân biệt block cipher và stream cipher.
13. Chữ ký số là gì? Cách thức thực hiện
14. Chứng minh OTP (One Time Pad) là thuật toán có tính chất perfect secrecy (theo định nghĩa của Shannon năm 1949)
15. Định nghĩa các loại mã độc thông dụng: worm, virus, trojan horse, rootkit 
16. Giải thích cơ chế hoạt động của Rootkit 
17. Mô tả một tấn công vào giao thức mã hoá WEP mà anh chị biết.
18. Trình bày tổng quan về client side honeypot và server side honeypot.  Giải thích hoạt động của honeypot Nepenthese.
19. Trình bày cách thức xác định mức độ tấn công từ chối dịch vụ dựa vào gói tin backscatter. Phân tích các ưu và nhược điểm của hướng tiếp cận xác định tấn công từ chối dịch vụ được mô tả trong công trình:”Inferring Internet Denial-of-Service Activity”.
20. Giải thích tác hại của các thuật toán Pseudorandom Generators không ngẩu nhiên nếu sử dụng tạo keystream trong stream cipher 

**Hình thức thi mở hay đóng vậy mọi người???**

**Comment by luongnguyenduc** [comment]
Thank a ve list cau hoi, em ko biet thi dong hay mo nua.

**Comment by Dunghanh** [comment]
tất cà tài liệu gói ghém trong một tờ giây a4 (mở)

**Comment by mickey123456** [comment]
Chỉ được mang theo một tờ a4 nhưng k được photo
Vào 07-04-2016 05:40, "Dunghanh" <notifications@github.com> đã viết:

**Comment by rinodung** [comment]
viết tay à, phong cách thầy hậu bá đạo quá

On Thu, Apr 7, 2016 at 7:05 AM, ThuyTTT <notifications@github.com> wrote:

> Chỉ được mang theo một tờ a4 nhưng k được photo
> Vào 07-04-2016 05:40, "Dunghanh" <notifications@github.com> đã viết:
>
> > tất cà tài liệu gói ghém trong một tờ giây a4 (mở)
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rinodung/webgoat/issues/19#issuecomment-206599366>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rinodung/webgoat/issues/19#issuecomment-206627266>
>



-- 
Đồng Tiến Dũng
01699938919
University of Information Technology

**Comment by mickey123456** [comment]
sếp của em mà

On Thu, Apr 7, 2016 at 10:52 AM, Dong Dung <notifications@github.com> wrote:

> viết tay à, phong cách thầy hậu bá đạo quá
>
> On Thu, Apr 7, 2016 at 7:05 AM, ThuyTTT <notifications@github.com> wrote:
>
> > Chỉ được mang theo một tờ a4 nhưng k được photo
> > Vào 07-04-2016 05:40, "Dunghanh" <notifications@github.com> đã viết:
> >
> > > tất cà tài liệu gói ghém trong một tờ giây a4 (mở)
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rinodung/webgoat/issues/19#issuecomment-206599366>
> >
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rinodung/webgoat/issues/19#issuecomment-206627266>
> >
>
>
>
> --
> Đồng Tiến Dũng
> 01699938919
> University of Information Technology
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rinodung/webgoat/issues/19#issuecomment-206685472>
>



-- 
Tran Thi Thu Thuy
Mobile: 0909.714.699

**Comment by rinodung** [comment]
hiện tại anh Phúng đã tập hợp được tương đối gần đủ câu ôn tập. anh chị em vào đây xem nhé.
https://drive.google.com/drive/u/1/folders/0BzEfYwv-4zwUTFNTd20tMURnZjQ

**Comment by Dunghanh** [comment]
cum on

**Comment by mickey123456** [comment]
Cám ơn nhe
Vào 12-04-2016 15:45, "Dunghanh" <notifications@github.com> đã viết:

**Comment by rinodung** [comment]
câu 8, 9 mọi người tự soạn nhé hết sức rồi.
[On thi ATBMTT.docx](https://github.com/rinodung/webgoat/files/215592/On.thi.ATBMTT.docx)

**Comment by luongnguyenduc** [comment]
Có ai còn thức ko, nén giúp em folder câu hỏi ôn tập môn này với, em ko có quyền access ;(

**Comment by rinodung** [comment]
Đây em nhé

On Wed, Apr 13, 2016 at 11:55 PM, luongnguyenduc <notifications@github.com>
wrote:

> Có ai còn thức ko, nén giúp em folder câu hỏi ôn tập môn này với, em ko có
> quyền access ;(
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rinodung/webgoat/issues/19#issuecomment-209544156>
>



-- 
Đồng Tiến Dũng
01699938919
University of Information Technology

**Comment by Dunghanh** [comment]
[CÂU HỎI ÔN TẬP AN TOÀN BẢO MẬT THÔNG TIN.docx](https://github.com/rinodung/webgoat/files/219944/CAU.H.I.ON.T.P.AN.TOAN.B.O.M.T.THONG.TIN.docx)

**Comment by Dunghanh** [comment]
XINLOI, BAY GIO MOI CHECK

**Comment by rinodung** [comment]
Báo cáo Word môn này

[SO SÁNH QUY TRÌNH KIỂM DUYỆT ỨNG DỤNG TRÊN ANDROID VÀ APPLE - CH1502028-CH1502029-CH1502042-CH1502035.docx](https://github.com/rinodung/webgoat/files/228319/SO.SANH.QUY.TRINH.KI.M.DUY.T.NG.D.NG.TREN.ANDROID.VA.APPLE.-.CH1502028-CH1502029-CH1502042-CH1502035.docx)

**Comment by Dunghanh** [comment]
cam on e

**Comment by rinodung** [comment]
Chị hạnh @Dunghanh  9
Chị Thúy @mickey123456  7.5 

[diem_an_toan_bao_mat_thong_tin-k_10_d2.pdf](https://github.com/rinodung/webgoat/files/360702/diem_an_toan_bao_mat_thong_tin-k_10_d2.pdf)

**Comment by mickey123456** [comment]
Hình như thầy cộng điểm sai rồi đó
Vào 13-07-2016 11:32, "Dong Dung" <notifications@github.com> đã viết:

**Comment by Dunghanh** [comment]
cum on
